### ISSUE TITLE
jME4 Roadmap

### ISSUE THREAD

**Issue by ItsMike54** [ItsMike54/Test-lib-for-jme4#1]
A sample roadmap for jme4 development.

- Vulkan Implementation
 - [x] AppSettings
 - [ ] Vulkan Instance Creation
 - [ ] Testing, a lot of testing
 - [ ] Implementing a "translator", that allows current jme code for OpenGL to work with Vulkan 
 rendering.
 - [ ] More tesing
 - [ ] /TO BE CONTINUED\

- /TO BE CONTINUED\
